# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  py38:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          - v1-dependencies-
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install -r requirements-test.txt
            sudo python -m pip install --upgrade secp256k1prp
      - run:
          name: run tests
          command: |
            ./cc-test-reporter before-build
            tox -e py38
            ./cc-test-reporter after-build --exit-code $?

  py39:
    docker:
      - image: circleci/python:3.9
    
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          - v1-dependencies-
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install -r requirements-test.txt
            sudo python -m pip install --upgrade secp256k1prp
      - run:
          name: run tests
          command: |
            ./cc-test-reporter before-build
            tox -e py39
            ./cc-test-reporter after-build --exit-code $?

  py310:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          - v1-dependencies-
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install -r requirements-test.txt
            sudo python -m pip install --upgrade secp256k1prp
      - run:
          name: run tests
          command: |
            ./cc-test-reporter before-build
            tox -e py310
            ./cc-test-reporter after-build --exit-code $?

  py311:
    docker:
      - image: circleci/python:3.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          - v1-dependencies-
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install -r requirements-test.txt
            sudo python -m pip install --upgrade secp256k1prp
      - run:
          name: run tests
          command: |
            ./cc-test-reporter before-build
            tox -e py311
            ./cc-test-reporter after-build --exit-code $?

  py312:
    docker:
      - image: circleci/python:3.12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          - v1-dependencies-
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install -r requirements-test.txt
            sudo python -m pip install --upgrade secp256k1prp
      - run:
          name: run tests
          command: |
            ./cc-test-reporter before-build
            tox -e py312
            ./cc-test-reporter after-build --exit-code $?

      # - deploy:
      #    name: Push coverage
      #    command: |
      #      if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #        tox -e upload_coverage
      #      fi

            
workflows:
  version: 2
  build:
    jobs:
      - py38
      - py39
      - py310
      - py311
      - py312
